/**
 * Regenerates src/components/anatomyPaths.js from the bodymap SVG sources in
 * scripts/anatomy/. Each SVG group id is mapped onto one of the app's muscle
 * keys (the same keys the exercise catalog in backend/src/lib/exercises.js
 * uses); non-muscle groups render in a neutral tone and the line art on top.
 *
 * Run with: node scripts/extract-anatomy.mjs (from frontend/)
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))

// Groups that are body scenery, not trackable muscles.
const NEUTRAL = new Set(['neck', 'feet', 'hands', 'groin'])

const FRONT_MAP = {
  'upper-trapezius': 'traps',
  gastrocnemius: 'calves',
  tibialis: 'calves',
  soleus: 'calves',
  'outer-quadricep': 'quads',
  'rectus-femoris': 'quads',
  'inner-quadricep': 'quads',
  'inner-thigh': 'quads',
  'wrist-extensors': 'forearms',
  'wrist-flexors': 'forearms',
  'long-head-bicep': 'biceps',
  'short-head-bicep': 'biceps',
  obliques: 'obliques',
  'lower-abdominals': 'abs',
  'upper-abdominals': 'abs',
  'mid-lower-pectoralis': 'chest',
  'upper-pectoralis': 'chest',
  'anterior-deltoid': 'shoulders',
  'lateral-deltoid': 'shoulders',
}

const BACK_MAP = {
  'upper-trapezius': 'traps',
  'lower-trapezius': 'traps',
  'traps-middle': 'traps',
  gastrocnemius: 'calves',
  soleus: 'calves',
  'medial-hamstrings': 'hamstrings',
  'lateral-hamstrings': 'hamstrings',
  'inner-thigh': 'hamstrings',
  'gluteus-maximus': 'glutes',
  'gluteus-medius': 'glutes',
  lowerback: 'lowerback',
  lats: 'lats',
  'wrist-extensors': 'forearms',
  'wrist-flexors': 'forearms',
  'medial-head-triceps': 'triceps',
  'long-head-triceps': 'triceps',
  'lateral-head-triceps': 'triceps',
  'lateral-deltoid': 'shoulders',
  'posterior-deltoid': 'shoulders',
}

const PATH_RE = /<path\b[^>]*?\bd="([^"]+)"/g

function parse(file, map) {
  const svg = fs.readFileSync(path.join(here, 'anatomy', file), 'utf8')
  const out = { strokeWidth: 3.5, muscles: {}, neutral: [], outline: { paths: [], lines: [] } }
  const sw = svg.match(/stroke-width="(3\.\d+)"/)
  if (sw) out.strokeWidth = Number(sw[1])
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]

  for (const part of svg.split(/<g\s/).slice(1)) {
    const header = part.slice(0, part.indexOf('>'))
    const id = (header.match(/id="([^"]+)"/) || [])[1]
    if (!id) continue // bare nested <g> inside the body group; handled by the body part
    if (id === 'body') {
      out.outline.paths.push(...[...part.matchAll(PATH_RE)].map((m) => m[1]))
      out.outline.lines.push(...[...part.matchAll(/<line ([^>]+)>/g)].map((m) => {
        const a = {}
        for (const [, k, v] of m[1].matchAll(/(x1|y1|x2|y2)="([^"]+)"/g)) a[k] = Number(v)
        return a
      }))
      continue
    }
    // Muscle groups never nest — split off the group's own content; stray
    // stroke paths between this group and the next belong to the line art.
    const end = part.indexOf('</g>')
    const content = end >= 0 ? part.slice(0, end) : part
    const tail = end >= 0 ? part.slice(end) : ''
    const paths = [...content.matchAll(PATH_RE)].map((m) => m[1])
    out.outline.paths.push(...[...tail.matchAll(PATH_RE)].map((m) => m[1]))
    if (NEUTRAL.has(id)) {
      out.neutral.push(...paths)
    } else {
      const key = map[id]
      if (!key) throw new Error(`${file}: group "${id}" has no muscle mapping`)
      out.muscles[key] = (out.muscles[key] || []).concat(paths)
    }
  }
  return { data: out, viewBox }
}

const front = parse('front.svg', FRONT_MAP)
const back = parse('back.svg', BACK_MAP)

const summary = (v) =>
  Object.entries(v.muscles).map(([k, p]) => `${k}:${p.length}`).join(' ') +
  ` | neutral:${v.neutral.length} outline:${v.outline.paths.length}p+${v.outline.lines.length}l sw:${v.strokeWidth}`
console.log('FRONT', summary(front.data))
console.log('BACK ', summary(back.data))

const banner = `/**
 * Path data for the front/back muscle anatomy figures, extracted from the
 * bodymap SVGs in scripts/anatomy/ (viewBox ${front.viewBox}). Muscle keys
 * match the exercise catalog in backend/src/lib/exercises.js. Generated by
 * scripts/extract-anatomy.mjs — edit the SVG sources and re-run it rather
 * than hand-editing path data.
 */
export const ANATOMY_VIEWBOX = '${front.viewBox}'

`
fs.writeFileSync(
  path.join(here, '..', 'src', 'components', 'anatomyPaths.js'),
  banner + `export const FRONT = ${JSON.stringify(front.data)}\n\nexport const BACK = ${JSON.stringify(back.data)}\n`,
)
console.log('written src/components/anatomyPaths.js')
